# Generated by Django 4.1.4 on 2023-02-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="can_edit",
            field=models.BooleanField(default=False),
        ),
    ]
