# Generated by Django 4.1.4 on 2023-01-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0003_remove_car_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showroom",
            name="unique_users",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unique_users",
                to="showroom.user",
            ),
        ),
    ]
