# Generated by Django 4.1.4 on 2023-01-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0006_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
