# Generated by Django 4.1.4 on 2023-01-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("showroom", "0007_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salehistory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_history_clients",
                to="showroom.client",
            ),
        ),
    ]
