version: '3.8'
services:  
  backend:
    container_name: backend
    volumes:
      - ./:/showroom
    build:
      context: ""
      dockerfile: Dockerfile
    command:  bash -c "python /showroom/manage.py migrate --noinput &&
              python /showroom/manage.py  runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    depends_on:
      - db


  db:
    restart: always
    image: postgres:14
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
