version: '3.8'
services:  
  db:
    restart: always
    image: postgres:14
    container_name: db
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data/ 
    # environment:
    #   - POSTGRES_DB=showroom
    #   - POSTGRES_USER=simmaksim
    #   - POSTGRES_PASSWORD=MSlizh2001
    env_file:
      - .env.dev
    expose:
      - "5432"
    ports:
      - '5432:5432'
    
  
  backend:
    container_name: backend
    build:
      context: ""
      dockerfile: Dockerfile
    command:  bash -c "python /showroom/manage.py migrate --noinput &&
              python /showroom/manage.py  runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    depends_on:
      - db